name: Zokou-MD 2.0

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Configure Git for HTTPS (fix Baileys)
      run: git config --global url."https://github.com/".insteadOf git@github.com

    - name: Install dependencies
      run: npm install

    - name: Install PM2 globally
      run: npm install pm2 -g

    - name: Start Zokou-MD with PM2
      run: pm2 start index.js --name zokou-md --watch --max-memory-restart 490M

    - name: Save PM2 process list
      run: pm2 save

    - name: Show PM2 logs
      run: pm2 logs zokou-md --lines 100
      continue-on-error: true

    - name: Keep bot running with env
      run: echo "Bot is running..."
      env:
        SESSION: ${{ secrets.SESSION }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        OWNER_NUMBER: ${{ secrets.OWNER_NUMBER }}
